set hive.map.aggr=true;

CREATE TABLE dest1(key INT) STORED AS TEXTFILE;

EXPLAIN
FROM src INSERT OVERWRITE TABLE dest1 SELECT count(1);

FROM src INSERT OVERWRITE TABLE dest1 SELECT count(1);

SELECT dest1.* FROM dest1;
