DROP TABLE TEST3a;
DROP TABLE TEST3b;
DROP TABLE TEST3c;
CREATE TABLE TEST3a(A INT, B FLOAT); 
DESCRIBE TEST3a; 
CREATE TABLE TEST3b(A ARRAY<INT>, B FLOAT, C MAP<FLOAT, INT>); 
DESCRIBE TEST3b; 
SHOW TABLES;
EXPLAIN
ALTER TABLE TEST3b ADD COLUMNS (X FLOAT);
ALTER TABLE TEST3b ADD COLUMNS (X FLOAT);
DESCRIBE TEST3b; 
EXPLAIN
ALTER TABLE TEST3b RENAME TO TEST3c;
ALTER TABLE TEST3b RENAME TO TEST3c;
DESCRIBE TEST3c; 
SHOW TABLES;
EXPLAIN
ALTER TABLE TEST3c REPLACE COLUMNS (R1 INT, R2 FLOAT);
ALTER TABLE TEST3c REPLACE COLUMNS (R1 INT, R2 FLOAT);
DESCRIBE EXTENDED TEST3c;
DROP TABLE TEST3c;
DROP TABLE TEST3a;
