DROP TABLE TEST2a;
CREATE TABLE TEST2a(A INT, B FLOAT) STORED AS TEXTFILE; 
DESCRIBE TEST2a; 
DROP TABLE TEST2b;
CREATE TABLE TEST2b(A ARRAY<INT>, B FLOAT, C MAP<FLOAT, INT>) STORED AS TEXTFILE; 
DESCRIBE TEST2b; 
SHOW TABLES;
DROP TABLE TEST2a;
SHOW TABLES;
DROP TABLE TEST2b;

EXPLAIN
SHOW TABLES;

