CREATE TABLE shtb_test1(KEY STRING, VALUE STRING) PARTITIONED BY(ds DATETIME) STORED AS TEXTFILE;
CREATE TABLE shtb_test2(KEY STRING, VALUE STRING) PARTITIONED BY(ds DATETIME) STORED AS TEXTFILE;

EXPLAIN
SHOW TABLES 'shtb_*';

SHOW TABLES 'shtb_*';

EXPLAIN
SHOW TABLES 'shtb_test1|shtb_test2';

SHOW TABLES 'shtb_test1|shtb_test2';

DROP TABLE shtb_test1;
DROP TABLE shtb_test2;
