<?php
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
include_once $GLOBALS['THRIFT_ROOT'].'/packages/serde/serde_types.php';

$GLOBALS['serde_CONSTANTS'] = array();

$GLOBALS['serde_CONSTANTS']['SERIALIZATION_LIB'] = 'serialization.lib';

$GLOBALS['serde_CONSTANTS']['SERIALIZATION_CLASS'] = 'serialization.class';

$GLOBALS['serde_CONSTANTS']['SERIALIZATION_FORMAT'] = 'serialization.format';

$GLOBALS['serde_CONSTANTS']['SERIALIZATION_DDL'] = 'serialization.ddl';

$GLOBALS['serde_CONSTANTS']['FIELD_DELIM'] = 'field.delim';

$GLOBALS['serde_CONSTANTS']['COLLECTION_DELIM'] = 'colelction.delim';

$GLOBALS['serde_CONSTANTS']['LINE_DELIM'] = 'line.delim';

$GLOBALS['serde_CONSTANTS']['MAPKEY_DELIM'] = 'mapkey.delim';

$GLOBALS['serde_CONSTANTS']['TINYINT_TYPE_NAME'] = 'tinyint';

$GLOBALS['serde_CONSTANTS']['INT_TYPE_NAME'] = 'int';

$GLOBALS['serde_CONSTANTS']['BIGINT_TYPE_NAME'] = 'bigint';

$GLOBALS['serde_CONSTANTS']['FLOAT_TYPE_NAME'] = 'float';

$GLOBALS['serde_CONSTANTS']['DOUBLE_TYPE_NAME'] = 'double';

$GLOBALS['serde_CONSTANTS']['STRING_TYPE_NAME'] = 'string';

$GLOBALS['serde_CONSTANTS']['DATE_TYPE_NAME'] = 'date';

$GLOBALS['serde_CONSTANTS']['DATETIME_TYPE_NAME'] = 'datetime';

$GLOBALS['serde_CONSTANTS']['TIMESTAMP_TYPE_NAME'] = 'timestamp';

$GLOBALS['serde_CONSTANTS']['LIST_TYPE_NAME'] = 'array';

$GLOBALS['serde_CONSTANTS']['MAP_TYPE_NAME'] = 'map';

$GLOBALS['serde_CONSTANTS']['PrimitiveTypes'] = array(
  'tinyint' => true,
  'int' => true,
  'bigint' => true,
  'float' => true,
  'double' => true,
  'string' => true,
  'date' => true,
  'datetime' => true,
  'timestamp' => true,
);

$GLOBALS['serde_CONSTANTS']['CollectionTypes'] = array(
  'array' => true,
  'map' => true,
);

?>
