/* Generated By:JJTree: Do not edit this line. DynamicSerDeSenumDef.java */

package org.apache.hadoop.hive.serde2.dynamic_type;

public class DynamicSerDeSenumDef extends SimpleNode {
  public DynamicSerDeSenumDef(int id) {
    super(id);
  }

  public DynamicSerDeSenumDef(thrift_grammar p, int id) {
    super(p, id);
  }

}
