/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.hadoop.yarn.api.records;

import java.text.NumberFormat;

public abstract class ContainerId implements Comparable<ContainerId>{
  public abstract ApplicationAttemptId getAppAttemptId();
  public abstract ApplicationId getAppId();
  public abstract int getId();
  
  public abstract void setAppAttemptId(ApplicationAttemptId atId);
  public abstract void setAppId(ApplicationId appID);
  public abstract void setId(int id);
 
  
  // TODO: Why thread local?
  // ^ NumberFormat instances are not threadsafe
  private static final ThreadLocal<NumberFormat> appIdFormat =
      new ThreadLocal<NumberFormat>() {
        @Override
        public NumberFormat initialValue() {
          NumberFormat fmt = NumberFormat.getInstance();
          fmt.setGroupingUsed(false);
          fmt.setMinimumIntegerDigits(4);
          return fmt;
        }
      };

  // TODO: fail the app submission if attempts are more than 10 or something
  private static final ThreadLocal<NumberFormat> appAttemptIdFormat =
      new ThreadLocal<NumberFormat>() {
        @Override
        public NumberFormat initialValue() {
          NumberFormat fmt = NumberFormat.getInstance();
          fmt.setGroupingUsed(false);
          fmt.setMinimumIntegerDigits(2);
          return fmt;
        }
      };
  // TODO: Why thread local?
  // ^ NumberFormat instances are not threadsafe
  private static final ThreadLocal<NumberFormat> containerIdFormat =
      new ThreadLocal<NumberFormat>() {
        @Override
        public NumberFormat initialValue() {
          NumberFormat fmt = NumberFormat.getInstance();
          fmt.setGroupingUsed(false);
          fmt.setMinimumIntegerDigits(6);
          return fmt;
        }
      };
  
  @Override
  public int hashCode() {
    // Generated by eclipse.
    final int prime = 31;
    int result = 1;
    result = prime * result + getId();
    result = prime * result
        + ((getAppAttemptId() == null) ? 0 : getAppAttemptId().hashCode());
    return result;
  }

  @Override
  public boolean equals(Object other) {
    if (other == null) {
      return false;
    }
    if (other.getClass().isAssignableFrom(this.getClass())) {
      ContainerId otherCId = (ContainerId)other;
      if (this.getAppAttemptId().equals(otherCId.getAppAttemptId())) {
        return this.getId() == otherCId.getId();
      }
    }
    return false;
  }

  @Override
  public int compareTo(ContainerId other) {
    if (this.getAppAttemptId().compareTo(other.getAppAttemptId()) == 0) {
      return this.getId() - other.getId();
    } else {
      return this.getAppAttemptId().compareTo(other.getAppAttemptId());
    }
    
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    ApplicationId appId = getAppId();
    sb.append("container_").append(appId.getClusterTimestamp()).append("_");
    sb.append(appIdFormat.get().format(appId.getId())).append("_");
    sb.append(appAttemptIdFormat.get().format(getAppAttemptId().
        getAttemptId())).append("_");
    sb.append(containerIdFormat.get().format(getId()));
    return sb.toString();
  }
}
