# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Dockerfile for installing the necessary dependencies for building Hadoop.
# See BUILDING.txt.

FROM rockylinux:8

WORKDIR /root

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

######
# Platform package dependency resolver
######
COPY pkg-resolver pkg-resolver
RUN chmod a+x pkg-resolver/*.sh pkg-resolver/*.py \
    && chmod a+r pkg-resolver/*.json

####
# Install EPEL
####
RUN pkg-resolver/install-epel.sh rockylinux:8

######
# Install packages from yum
######
# hadolint ignore=DL3008,SC2046
RUN yum update -y \
    && yum install -y python3 \
    && yum install -y $(pkg-resolver/resolve.py rockylinux:8)

RUN update-alternatives --set java java-17-openjdk.x86_64

RUN dnf --enablerepo=powertools install -y \
    doxygen \
    snappy-devel \
    yasm

RUN dnf install -y \
    bouncycastle \
    gcc-toolset-9-gcc \
    gcc-toolset-9-gcc-c++ \
    libpmem-devel

# Set GCC 9 as the default C/C++ compiler
RUN echo "source /opt/rh/gcc-toolset-9/enable" >> /etc/bashrc
SHELL ["/bin/bash", "--login", "-c"]

######
# Set the environment variables needed for CMake
# to find and use GCC 9 for compilation
######
ENV GCC_HOME="/opt/rh/gcc-toolset-9"
ENV CC="${GCC_HOME}/root/usr/bin/gcc"
ENV CXX="${GCC_HOME}/root/usr/bin/g++"
ENV MODULES_RUN_QUARANTINE="LD_LIBRARY_PATH LD_PRELOAD"
ENV MODULES_CMD="/usr/share/Modules/libexec/modulecmd.tcl"
ENV SHLVL=1
ENV MODULEPATH="/etc/scl/modulefiles:/usr/share/Modules/modulefiles:/etc/modulefiles:/usr/share/modulefiles"
ENV MODULEPATH_modshare="/usr/share/modulefiles:1:/usr/share/Modules/modulefiles:1:/etc/modulefiles:1"
ENV MODULESHOME="/usr/share/Modules"
ENV LD_LIBRARY_PATH="${GCC_HOME}/root/usr/lib64:${GCC_HOME}/root/usr/lib:${GCC_HOME}/root/usr/lib64/dyninst:${GCC_HOME}/root/usr/lib/dyninst:${GCC_HOME}/root/usr/lib64:${GCC_HOME}/root/usr/lib:/usr/lib:/usr/lib64"
ENV PCP_DIR="${GCC_HOME}/root"
ENV MANPATH="${GCC_HOME}/root/usr/share/man::"
ENV PATH="${GCC_HOME}/root/usr/bin:/usr/share/Modules/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
ENV PKG_CONFIG_PATH="${GCC_HOME}/root/usr/lib64/pkgconfig"
ENV INFOPATH="${GCC_HOME}/root/usr/share/info"

# TODO: Set locale

######
# Set env vars required to build Hadoop
######
ENV MAVEN_HOME=/opt/maven
ENV PATH="${PATH}:${MAVEN_HOME}/bin"

# jenkins.sh sets --java-home to a path with an "-amd64" suffix, which doesn't
# exist on Rocky. Fake it with symlinks.
RUN ln -s /usr/lib/jvm/java-17-openjdk /usr/lib/jvm/java-17-openjdk-amd64
RUN ln -s /usr/lib/jvm/java-21-openjdk /usr/lib/jvm/java-21-openjdk-amd64

# JAVA_HOME must be set in Maven >= 3.5.0 (MNG-6003)
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk

#######
# Set env vars for SpotBugs
#######
ENV SPOTBUGS_HOME=/opt/spotbugs

#######
# Set env vars for Google Protobuf 3.25.5
#######
ENV PROTOBUF_HOME=/opt/protobuf
ENV PATH="${PATH}:${PROTOBUF_HOME}/bin"

# Skip gpg verification when downloading Yetus via yetus-wrapper
ENV HADOOP_SKIP_YETUS_VERIFICATION=true

######
# Install packages
######
RUN pkg-resolver/install-maven.sh rockylinux:8
RUN pkg-resolver/install-boost.sh rockylinux:8
RUN pkg-resolver/install-spotbugs.sh rockylinux:8
RUN pkg-resolver/install-protobuf.sh rockylinux:8
RUN pkg-resolver/install-intel-isa-l.sh rockylinux:8
RUN pkg-resolver/install-common-pkgs.sh

###
# Everything past this point is either not needed for testing or breaks Yetus.
# So tell Yetus not to read the rest of the file:
# YETUS CUT HERE
###

# Add a welcome message and environment checks.
COPY hadoop_env_checks.sh /root/hadoop_env_checks.sh
RUN chmod 755 /root/hadoop_env_checks.sh
# hadolint ignore=SC2016
RUN echo '${HOME}/hadoop_env_checks.sh' >> /root/.bashrc
