/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package org.apache.hadoop.hive.metastore.api;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.Set;
import java.util.HashSet;
import com.facebook.thrift.*;

import com.facebook.thrift.protocol.*;
import com.facebook.thrift.transport.*;

public class SerDeInfo implements TBase, java.io.Serializable {
private String name;
private String serializationLib;
private Map<String,String> parameters;

public final Isset __isset = new Isset();
public static final class Isset implements java.io.Serializable {
public boolean name = false;
public boolean serializationLib = false;
public boolean parameters = false;
}

public SerDeInfo() {
}

public SerDeInfo(
String name,
String serializationLib,
Map<String,String> parameters)
{
this();
this.name = name;
this.__isset.name = true;
this.serializationLib = serializationLib;
this.__isset.serializationLib = true;
this.parameters = parameters;
this.__isset.parameters = true;
}

public String getName() {
return this.name;
}

public void setName(String name) {
this.name = name;
this.__isset.name = true;
}

public void unsetName() {
this.__isset.name = false;
}

public String getSerializationLib() {
return this.serializationLib;
}

public void setSerializationLib(String serializationLib) {
this.serializationLib = serializationLib;
this.__isset.serializationLib = true;
}

public void unsetSerializationLib() {
this.__isset.serializationLib = false;
}

public int getParametersSize() {
return (this.parameters == null) ? 0 : this.parameters.size();
}

public void putToParameters(String key, String val) {
if (this.parameters == null) {
this.parameters = new HashMap<String,String>();
}
this.parameters.put(key, val);
this.__isset.parameters = true;
}

public Map<String,String> getParameters() {
return this.parameters;
}

public void setParameters(Map<String,String> parameters) {
this.parameters = parameters;
this.__isset.parameters = true;
}

public void unsetParameters() {
this.parameters = null;
this.__isset.parameters = false;
}

public boolean equals(Object that) {
if (that == null)
  return false;
if (that instanceof SerDeInfo)
  return this.equals((SerDeInfo)that);
return false;
}

public boolean equals(SerDeInfo that) {
if (that == null)
  return false;

boolean this_present_name = true && (this.name != null);
boolean that_present_name = true && (that.name != null);
if (this_present_name || that_present_name) {
if (!(this_present_name && that_present_name))
  return false;
if (!this.name.equals(that.name))
  return false;
}

boolean this_present_serializationLib = true && (this.serializationLib != null);
boolean that_present_serializationLib = true && (that.serializationLib != null);
if (this_present_serializationLib || that_present_serializationLib) {
if (!(this_present_serializationLib && that_present_serializationLib))
  return false;
if (!this.serializationLib.equals(that.serializationLib))
  return false;
}

boolean this_present_parameters = true && (this.parameters != null);
boolean that_present_parameters = true && (that.parameters != null);
if (this_present_parameters || that_present_parameters) {
if (!(this_present_parameters && that_present_parameters))
  return false;
if (!this.parameters.equals(that.parameters))
  return false;
}

return true;
}

public int hashCode() {
return 0;
}

public void read(TProtocol iprot) throws TException {
TField field;
iprot.readStructBegin();
while (true)
{
field = iprot.readFieldBegin();
if (field.type == TType.STOP) { 
  break;
}
switch (field.id)
{
  case 1:
    if (field.type == TType.STRING) {
      this.name = iprot.readString();
      this.__isset.name = true;
    } else { 
      TProtocolUtil.skip(iprot, field.type);
    }
    break;
  case 2:
    if (field.type == TType.STRING) {
      this.serializationLib = iprot.readString();
      this.__isset.serializationLib = true;
    } else { 
      TProtocolUtil.skip(iprot, field.type);
    }
    break;
  case 3:
    if (field.type == TType.MAP) {
      {
        TMap _map4 = iprot.readMapBegin();
        this.parameters = new HashMap<String,String>(2*_map4.size);
        for (int _i5 = 0; _i5 < _map4.size; ++_i5)
        {
          String _key6;
          String _val7;
          _key6 = iprot.readString();
          _val7 = iprot.readString();
          this.parameters.put(_key6, _val7);
        }
        iprot.readMapEnd();
      }
      this.__isset.parameters = true;
    } else { 
      TProtocolUtil.skip(iprot, field.type);
    }
    break;
  default:
    TProtocolUtil.skip(iprot, field.type);
    break;
}
iprot.readFieldEnd();
}
iprot.readStructEnd();
}

public void write(TProtocol oprot) throws TException {
TStruct struct = new TStruct("SerDeInfo");
oprot.writeStructBegin(struct);
TField field = new TField();
if (this.name != null) {
field.name = "name";
field.type = TType.STRING;
field.id = 1;
oprot.writeFieldBegin(field);
oprot.writeString(this.name);
oprot.writeFieldEnd();
}
if (this.serializationLib != null) {
field.name = "serializationLib";
field.type = TType.STRING;
field.id = 2;
oprot.writeFieldBegin(field);
oprot.writeString(this.serializationLib);
oprot.writeFieldEnd();
}
if (this.parameters != null) {
field.name = "parameters";
field.type = TType.MAP;
field.id = 3;
oprot.writeFieldBegin(field);
{
  oprot.writeMapBegin(new TMap(TType.STRING, TType.STRING, this.parameters.size()));
  for (String _iter8 : this.parameters.keySet())  {
    oprot.writeString(_iter8);
    oprot.writeString(this.parameters.get(_iter8));
  }
  oprot.writeMapEnd();
}
oprot.writeFieldEnd();
}
oprot.writeFieldStop();
oprot.writeStructEnd();
}

public String toString() {
StringBuilder sb = new StringBuilder("SerDeInfo(");
sb.append("name:");
sb.append(this.name);
sb.append(",serializationLib:");
sb.append(this.serializationLib);
sb.append(",parameters:");
sb.append(this.parameters);
sb.append(")");
return sb.toString();
}

}

