<?php
/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
include_once $GLOBALS['THRIFT_ROOT'].'/packages/hive_metastore/hive_metastore_types.php';

$GLOBALS['hive_metastore_CONSTANTS'] = array();

$GLOBALS['hive_metastore_CONSTANTS']['META_SERDE'] = 'com.facebook.serde.simple_meta.MetadataTypedColumnsetSerDe';

$GLOBALS['hive_metastore_CONSTANTS']['META_TABLE_COLUMNS'] = 'columns';

$GLOBALS['hive_metastore_CONSTANTS']['BUCKET_FIELD_NAME'] = 'bucket_field_name';

$GLOBALS['hive_metastore_CONSTANTS']['BUCKET_COUNT'] = 'bucket_count';

$GLOBALS['hive_metastore_CONSTANTS']['FIELD_TO_DIMENSION'] = 'field_to_dimension';

$GLOBALS['hive_metastore_CONSTANTS']['META_TABLE_NAME'] = 'name';

$GLOBALS['hive_metastore_CONSTANTS']['META_TABLE_DB'] = 'db';

$GLOBALS['hive_metastore_CONSTANTS']['META_TABLE_LOCATION'] = 'location';

$GLOBALS['hive_metastore_CONSTANTS']['META_TABLE_SERDE'] = 'serde';

$GLOBALS['hive_metastore_CONSTANTS']['SERIALIZATION_FORMAT'] = 'serialization.format';

$GLOBALS['hive_metastore_CONSTANTS']['SERIALIZATION_CLASS'] = 'serialization.class';

$GLOBALS['hive_metastore_CONSTANTS']['SERIALIZATION_LIB'] = 'serialization.lib';

$GLOBALS['hive_metastore_CONSTANTS']['META_TABLE_PARTITION_COLUMNS'] = 'partition_columns';

$GLOBALS['hive_metastore_CONSTANTS']['FILE_INPUT_FORMAT'] = 'file.inputformat';

$GLOBALS['hive_metastore_CONSTANTS']['FILE_OUTPUT_FORMAT'] = 'file.outputformat';

$GLOBALS['hive_metastore_CONSTANTS']['KEY_COMMENTS'] = 'key_comments';

$GLOBALS['hive_metastore_CONSTANTS']['VERSION_0_1'] = '0.1';

$GLOBALS['hive_metastore_CONSTANTS']['TINYINT_TYPE_NAME'] = 'tinyint';

$GLOBALS['hive_metastore_CONSTANTS']['INT_TYPE_NAME'] = 'int';

$GLOBALS['hive_metastore_CONSTANTS']['BIGINT_TYPE_NAME'] = 'bigint';

$GLOBALS['hive_metastore_CONSTANTS']['FLOAT_TYPE_NAME'] = 'float';

$GLOBALS['hive_metastore_CONSTANTS']['DOUBLE_TYPE_NAME'] = 'double';

$GLOBALS['hive_metastore_CONSTANTS']['STRING_TYPE_NAME'] = 'string';

$GLOBALS['hive_metastore_CONSTANTS']['DATE_TYPE_NAME'] = 'date';

$GLOBALS['hive_metastore_CONSTANTS']['DATETIME_TYPE_NAME'] = 'datetime';

$GLOBALS['hive_metastore_CONSTANTS']['TIMESTAMP_TYPE_NAME'] = 'timestamp';

$GLOBALS['hive_metastore_CONSTANTS']['LIST_TYPE_NAME'] = 'list';

$GLOBALS['hive_metastore_CONSTANTS']['MAP_TYPE_NAME'] = 'map';

$GLOBALS['hive_metastore_CONSTANTS']['PrimitiveTypes'] = array(
  'tinyint' => true,
  'int' => true,
  'bigint' => true,
  'float' => true,
  'double' => true,
  'string' => true,
  'date' => true,
  'datetime' => true,
  'timestamp' => true,
);

$GLOBALS['hive_metastore_CONSTANTS']['CollectionTypes'] = array(
  'list' => true,
  'map' => true,
);

?>
