package org.apache.hadoop.mapreduce.v2.api.records;

public enum TaskAttemptState {
  NEW, 
  UNASSIGNED, 
  ASSIGNED, 
  RUNNING, 
  COMMIT_PENDING, 
  SUCCESS_CONTAINER_CLEANUP, 
  SUCCEEDED, 
  FAIL_CONTAINER_CLEANUP, 
  FAIL_TASK_CLEANUP, 
  FAILED, 
  KILL_CONTAINER_CLEANUP, 
  KILL_TASK_CLEANUP, 
  KILLED
}
