#!/bin/bash

sleep 1
for ((java_process=$((`ps -ef|grep java|wc|awk '{print $1}'`-1)); \
      java_process > 60; \
      java_process=$((`ps -ef|grep java|wc|awk '{print $1}'`-1))))
do
    sleep 10
    echo $java_process
done

