#!/usr/bin/env bash

GRID_DIR=`dirname "$0"`
GRID_DIR=`cd "$GRID_DIR"; pwd`
source $GRID_DIR/../gridmix-env

for ((i=0; i < $NUM_OF_SMALL_JOBS_PER_CLASS; i++))
do
    echo $i
    hod $SMALL_JOB_HOD_OPTIONS --hod.script=$GRID_MIX_HOME/pipesort/text-sort.small  2>&1 > pipesort.small.$i.out &
    $GRID_MIX_HOME/submissionScripts/sleep_if_too_busy
    hod $SMALL_JOB_HOD_OPTIONS --hod.script=$GRID_MIX_HOME/streamsort/text-sort.small  2>&1 > streamsort.small.$i.out &
    $GRID_MIX_HOME/submissionScripts/sleep_if_too_busy
    hod $SMALL_JOB_HOD_OPTIONS --hod.script=$GRID_MIX_HOME/javasort/text-sort.small  2>&1 > javasort.small.$i.out  &
    $GRID_MIX_HOME/submissionScripts/sleep_if_too_busy
done
    
for ((i=0; i < $NUM_OF_MEDIUM_JOBS_PER_CLASS; i++))
do
    echo $i
    hod $MEDIUM_JOB_HOD_OPTIONS --hod.script=$GRID_MIX_HOME/pipesort/text-sort.medium  2>&1 > pipesort.medium.$i.out &
    $GRID_MIX_HOME/submissionScripts/sleep_if_too_busy
    hod $MEDIUM_JOB_HOD_OPTIONS --hod.script=$GRID_MIX_HOME/streamsort/text-sort.medium  2>&1 > streamsort.medium.$i.out &
    $GRID_MIX_HOME/submissionScripts/sleep_if_too_busy
    hod $MEDIUM_JOB_HOD_OPTIONS --hod.script=$GRID_MIX_HOME/javasort/text-sort.medium  2>&1 > javasort.medium.$i.out  &
    $GRID_MIX_HOME/submissionScripts/sleep_if_too_busy
done

for ((i=0; i < $NUM_OF_LARGE_JOBS_PER_CLASS; i++))
do
    echo $i
    hod $LARGE_JOB_HOD_OPTIONS --hod.script=$GRID_MIX_HOME/pipesort/text-sort.large  2>&1 >  pipesort.large.$i.out &
    $GRID_MIX_HOME/submissionScripts/sleep_if_too_busy
    hod $LARGE_JOB_HOD_OPTIONS --hod.script=$GRID_MIX_HOME/streamsort/text-sort.large  2>&1 > streamsort.large.$i.out &
    $GRID_MIX_HOME/submissionScripts/sleep_if_too_busy
    hod $LARGE_JOB_HOD_OPTIONS --hod.script=$GRID_MIX_HOME/javasort/text-sort.large  2>&1 > javasort.large.$i.out &
    $GRID_MIX_HOME/submissionScripts/sleep_if_too_busy
done
    
