/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* Generated By:JJTree: Do not edit this line. /home/pwyckoff/projects/hadoop/trunk/src/org.apache.hadoop.hive.serde/build/thrift_grammarTreeConstants.java */

package org.apache.hadoop.hive.serde.dynamic_type;

public interface thrift_grammarTreeConstants
{
  public int JJTSTART = 0;
  public int JJTHEADERLIST = 1;
  public int JJTHEADER = 2;
  public int JJTNAMESPACE = 3;
  public int JJTINCLUDE = 4;
  public int JJTDEFINITION = 5;
  public int JJTTYPEDEFINITION = 6;
  public int JJTTYPEDEF = 7;
  public int JJTCOMMAORSEMICOLON = 8;
  public int JJTENUM = 9;
  public int JJTENUMDEFLIST = 10;
  public int JJTENUMDEF = 11;
  public int JJTSENUM = 12;
  public int JJTSENUMDEFLIST = 13;
  public int JJTSENUMDEF = 14;
  public int JJTCONST = 15;
  public int JJTCONSTVALUE = 16;
  public int JJTCONSTLIST = 17;
  public int JJTCONSTLISTCONTENTS = 18;
  public int JJTCONSTMAP = 19;
  public int JJTCONSTMAPCONTENTS = 20;
  public int JJTSTRUCT = 21;
  public int JJTXCEPTION = 22;
  public int JJTSERVICE = 23;
  public int JJTFLAGARGS = 24;
  public int JJTUNFLAGARGS = 25;
  public int JJTEXTENDS = 26;
  public int JJTFUNCTION = 27;
  public int JJTASYNC = 28;
  public int JJTTHROWS = 29;
  public int JJTFIELDLIST = 30;
  public int JJTFIELD = 31;
  public int JJTFIELDREQUIREDNESS = 32;
  public int JJTFIELDVALUE = 33;
  public int JJTDEFINITIONTYPE = 34;
  public int JJTFUNCTIONTYPE = 35;
  public int JJTFIELDTYPE = 36;
  public int JJTTYPESTRING = 37;
  public int JJTTYPEBYTE = 38;
  public int JJTTYPEI16 = 39;
  public int JJTTYPEI32 = 40;
  public int JJTTYPEI64 = 41;
  public int JJTTYPEDOUBLE = 42;
  public int JJTTYPEBOOL = 43;
  public int JJTTYPEMAP = 44;
  public int JJTTYPESET = 45;
  public int JJTTYPELIST = 46;


  public String[] jjtNodeName = {
    "Start",
    "HeaderList",
    "Header",
    "Namespace",
    "Include",
    "Definition",
    "TypeDefinition",
    "Typedef",
    "CommaOrSemicolon",
    "Enum",
    "EnumDefList",
    "EnumDef",
    "Senum",
    "SenumDefList",
    "SenumDef",
    "Const",
    "ConstValue",
    "ConstList",
    "ConstListContents",
    "ConstMap",
    "ConstMapContents",
    "Struct",
    "Xception",
    "Service",
    "FlagArgs",
    "UnflagArgs",
    "Extends",
    "Function",
    "Async",
    "Throws",
    "FieldList",
    "Field",
    "FieldRequiredness",
    "FieldValue",
    "DefinitionType",
    "FunctionType",
    "FieldType",
    "TypeString",
    "TypeByte",
    "Typei16",
    "Typei32",
    "Typei64",
    "TypeDouble",
    "TypeBool",
    "TypeMap",
    "TypeSet",
    "TypeList",
  };
}
