#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

from thrift.Thrift import *
from ttypes import *

SERIALIZATION_LIB = 'serialization.lib'

SERIALIZATION_CLASS = 'serialization.class'

SERIALIZATION_FORMAT = 'serialization.format'

SERIALIZATION_DDL = 'serialization.ddl'

