// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/tensorflow_server.proto

package org.tensorflow.distruntime;

public interface ServerDefOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tensorflow.ServerDef)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The cluster of which this server is a member.
   * </pre>
   *
   * <code>optional .tensorflow.ClusterDef cluster = 1;</code>
   */
  boolean hasCluster();
  /**
   * <pre>
   * The cluster of which this server is a member.
   * </pre>
   *
   * <code>optional .tensorflow.ClusterDef cluster = 1;</code>
   */
  org.tensorflow.distruntime.ClusterDef getCluster();
  /**
   * <pre>
   * The cluster of which this server is a member.
   * </pre>
   *
   * <code>optional .tensorflow.ClusterDef cluster = 1;</code>
   */
  org.tensorflow.distruntime.ClusterDefOrBuilder getClusterOrBuilder();

  /**
   * <pre>
   * The name of the job of which this server is a member.
   * NOTE(mrry): The `cluster` field must contain a `JobDef` with a `name` field
   * that matches this name.
   * </pre>
   *
   * <code>optional string job_name = 2;</code>
   */
  java.lang.String getJobName();
  /**
   * <pre>
   * The name of the job of which this server is a member.
   * NOTE(mrry): The `cluster` field must contain a `JobDef` with a `name` field
   * that matches this name.
   * </pre>
   *
   * <code>optional string job_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getJobNameBytes();

  /**
   * <pre>
   * The task index of this server in its job.
   * NOTE: The `cluster` field must contain a `JobDef` with a matching `name`
   * and a mapping in its `tasks` field for this index.
   * </pre>
   *
   * <code>optional int32 task_index = 3;</code>
   */
  int getTaskIndex();

  /**
   * <pre>
   * The default configuration for sessions that run on this server.
   * </pre>
   *
   * <code>optional .tensorflow.ConfigProto default_session_config = 4;</code>
   */
  boolean hasDefaultSessionConfig();
  /**
   * <pre>
   * The default configuration for sessions that run on this server.
   * </pre>
   *
   * <code>optional .tensorflow.ConfigProto default_session_config = 4;</code>
   */
  org.tensorflow.framework.ConfigProto getDefaultSessionConfig();
  /**
   * <pre>
   * The default configuration for sessions that run on this server.
   * </pre>
   *
   * <code>optional .tensorflow.ConfigProto default_session_config = 4;</code>
   */
  org.tensorflow.framework.ConfigProtoOrBuilder getDefaultSessionConfigOrBuilder();

  /**
   * <pre>
   * The protocol to be used by this server.
   * Acceptable values include: "grpc".
   * </pre>
   *
   * <code>optional string protocol = 5;</code>
   */
  java.lang.String getProtocol();
  /**
   * <pre>
   * The protocol to be used by this server.
   * Acceptable values include: "grpc".
   * </pre>
   *
   * <code>optional string protocol = 5;</code>
   */
  com.google.protobuf.ByteString
      getProtocolBytes();
}
