CREATE TABLE DEST1(key INT, value STRING);
CREATE TABLE DEST2(key INT, value STRING);

FROM SRC
INSERT OVERWRITE TABLE DEST1 SELECT SRC.key, sum(SUBSTR(SRC.value,4)) GROUP BY SRC.key
INSERT OVERWRITE TABLE DEST2 SELECT SRC.key, sum(SUBSTR(SRC.value,4)) GROUP BY SRC.key;

SELECT DEST1.* FROM DEST1;
SELECT DEST1.* FROM DEST2;
