CREATE TABLE TEST2a(A INT, B FLOAT); 
DESCRIBE TEST2a; 
CREATE TABLE TEST2b(A ARRAY<INT>, B FLOAT, C MAP<FLOAT, INT>); 
DESCRIBE TEST2b; 
SHOW TABLES;
DROP TABLE TEST2a;
SHOW TABLES;
DROP TABLE TEST2b;

EXPLAIN
SHOW TABLES;

