#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Image Cache

# Security: write privileges are safe since this is triggered only by
# `push` and `workflow_dispatch` (implying user has write access).
on:
  # Run jobs when a commit is merged
  push:
    branches:
      - 'trunk'
      - 'branch-*'
    paths:
      - 'dev-support/docker/**'
  workflow_dispatch:

jobs:
  build-image-cache-ubuntu_24:
    permissions:
      packages: write
    name: Run
    uses: ./.github/workflows/tmpl_build_image_cache.yml
    with:
      os: ubuntu_24
  build-image-cache-debian_13:
    permissions:
      packages: write
    name: Run
    uses: ./.github/workflows/tmpl_build_image_cache.yml
    with:
      os: debian_13
  build-image-cache-rockylinux_8:
    permissions:
      packages: write
    name: Run
    uses: ./.github/workflows/tmpl_build_image_cache.yml
    with:
      os: rockylinux_8
